### PR TITLE
Update/fix readme

### PR DESCRIPTION
**Pull request by patosullivan**
Necessary and helpful changes to the readme.

### CODE REVIEW

**Comment by matthiasschaub** [comment]
Nice addition. I think it would be very helpful to get more context about how to setup the hoon-language-server. Similar to https://github.com/urbitme/hoon-language-server

I think the config snipped in this PR could be simpler since the `lspconfig` comes with 


```
lua << EOF
require'lspconfig'.hoon_ls.setup{
  cmd = {"hoon-language-server" "-p", "80", "-d", "500", -s "zod", "-u", "http://localhost", "-c" "lidlut-tabwed-pillex-ridrup"},
  filetypes = {"hoon"},
  single_file_support = true
}
EOF
```

**Comment by matthiasschaub** [comment]
Nice addition. I think it would be very helpful to get more context about how to setup the hoon-language-server. Similar to https://github.com/urbitme/hoon-language-server

I think the config snipped in this PR could be simpler since the `lspconfig` comes provides default configs.

Lua:
```lua
require('lspconfig').hoon_ls.setup{}
```

**Comment by ryjm** [comment]
> 

should probably just merge in the changes from urbitme too

**Comment by patosullivan** [comment]
Closing in favor of #25

**Pull request closed without merging**
